FROM php:apache

RUN docker-php-ext-install pdo pdo_mysql
RUN a2enmod rewrite

COPY . /var/www/html/

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80

# RUN npm install -g npx
# RUN npx tailwindcss init
# RUN npx tailwindcss -i .\public\input.css -o .\public\style.css --watch