services:
  code:
    image: php:apache
    build: .
    container_name: web-page
    ports:
      - '3000:80'
    volumes:
      - ./src/index.php:/var/www/html/index.php
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: '123456'
      MARIADB_DATABASE: 'week4-database'
      MARIADB_USER: 'week4'
      MARIADB_PASSWORD: '123456'
    ports:
      - "3307:3306"
    volumes:
      - mariadb:/var/lib/mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: week4-phpmyadmin
    restart: always
    environment:
      PMA_HOST: 'database'
      PMA_PORT: '3306'
    ports:
      - "8080:80"

volumes:
  mariadb:
